{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.136.1202.0 (24.09)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dim_product\",\"dim_customer_cemographic\",\"dim_shiping_carriers\",\"dim_suppliers_name\",\"dim_location\",\"dim_inspection_result\",\"dim_transportation_mode\",\"dim_routes\",\"Fact_supply_data\",\"_measures\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "AutoDetected_ee9f2f1b-9a06-4c93-af5f-54d140174b6e",
        "fromColumn": "product_id",
        "fromTable": "Fact_supply_data",
        "toColumn": "product_id",
        "toTable": "dim_product"
      },
      {
        "name": "AutoDetected_a41184fb-fa91-41f8-86d1-107eb278196b",
        "fromColumn": "cust_demo_id",
        "fromTable": "Fact_supply_data",
        "toColumn": "cust_demo_id",
        "toTable": "dim_customer_cemographic"
      },
      {
        "name": "AutoDetected_716e2312-9deb-4a3c-b5fd-75876315d4f5",
        "fromColumn": "ship_carriers_id",
        "fromTable": "Fact_supply_data",
        "toColumn": "ship_carriers_id",
        "toTable": "dim_shiping_carriers"
      },
      {
        "name": "AutoDetected_617433f1-cc37-4f05-994c-9d4983839df9",
        "fromColumn": "supplier_id",
        "fromTable": "Fact_supply_data",
        "toColumn": "supplier_id",
        "toTable": "dim_suppliers_name"
      },
      {
        "name": "AutoDetected_f5fc0266-5219-4f09-8b2f-25204bc712eb",
        "fromColumn": "location_id",
        "fromTable": "Fact_supply_data",
        "toColumn": "location_id",
        "toTable": "dim_location"
      },
      {
        "name": "AutoDetected_0b620aa2-e880-464d-952c-b359ebc713dd",
        "fromColumn": "inspection_id",
        "fromTable": "Fact_supply_data",
        "toColumn": "inspection_id",
        "toTable": "dim_inspection_result"
      },
      {
        "name": "AutoDetected_c04326fd-a9bc-4bc6-beb2-8ef82e633657",
        "fromColumn": "transportation_id",
        "fromTable": "Fact_supply_data",
        "toColumn": "transportation_id",
        "toTable": "dim_transportation_mode"
      },
      {
        "name": "AutoDetected_8c811a7f-abe3-43b1-b751-92f1db3a85e4",
        "fromColumn": "routes_id",
        "fromTable": "Fact_supply_data",
        "toColumn": "routes_id",
        "toTable": "dim_routes"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "dim_product",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Product type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "0de8ba58-9f4a-49f9-b301-71c442d72bfb",
            "sortByColumn": "product_id",
            "sourceColumn": "Product type",
            "summarizeBy": "none"
          },
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "a274b2e6-c843-44f7-9422-09c19d9c0676",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3f6f7f4e-9eec-4e61-8f3d-ed800c844819",
        "partitions": [
          {
            "name": "dim_product",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"H:\\_Portfolio Project Github\\Supply Chain Dashboard\\Supply Chain Dashboard Live.xlsx\"), null, true),",
                "    supply_chain_data_Sheet = Source{[Item=\"supply_chain_data\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(supply_chain_data_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Product type\", type text}, {\"SKU\", type text}, {\"Price\", type number}, {\"Availability\", Int64.Type}, {\"Number of products sold\", Int64.Type}, {\"Revenue generated\", type number}, {\"Customer demographics\", type text}, {\"Stock levels\", Int64.Type}, {\"Lead times\", Int64.Type}, {\"Order quantities\", Int64.Type}, {\"Shipping times\", Int64.Type}, {\"Shipping carriers\", type text}, {\"Shipping costs\", type number}, {\"Supplier name\", type text}, {\"Location\", type text}, {\"Lead time\", Int64.Type}, {\"Production volumes\", Int64.Type}, {\"Manufacturing lead time\", Int64.Type}, {\"Manufacturing costs\", type number}, {\"Inspection results\", type text}, {\"Defect rates\", type number}, {\"Transportation modes\", type text}, {\"Routes\", type text}, {\"Costs\", type number}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"Product type\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Removed Duplicates\", \"Custom\", each if [Product type] = \"haircare\" then 1 else if [Product type] = \"skincare\" then 2 else if [Product type] = \"cosmetics\" then 3 else null, type number),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Conditional Column\",{{\"Custom\", \"product_id\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_customer_cemographic",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Customer demographics",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "332681f5-7e1c-414c-88b3-142b12bd5c7f",
            "sourceColumn": "Customer demographics",
            "summarizeBy": "none"
          },
          {
            "name": "cust_demo_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "c43a15d0-3e65-4f76-a798-558a92d02af2",
            "sourceColumn": "cust_demo_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "690febd1-b98d-4366-927f-05bedaa85f14",
        "partitions": [
          {
            "name": "dim_customer_cemographic",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"H:\\_Portfolio Project Github\\Supply Chain Dashboard\\Supply Chain Dashboard Live.xlsx\"), null, true),",
                "    supply_chain_data_Sheet = Source{[Item=\"supply_chain_data\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(supply_chain_data_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Product type\", type text}, {\"SKU\", type text}, {\"Price\", type number}, {\"Availability\", Int64.Type}, {\"Number of products sold\", Int64.Type}, {\"Revenue generated\", type number}, {\"Customer demographics\", type text}, {\"Stock levels\", Int64.Type}, {\"Lead times\", Int64.Type}, {\"Order quantities\", Int64.Type}, {\"Shipping times\", Int64.Type}, {\"Shipping carriers\", type text}, {\"Shipping costs\", type number}, {\"Supplier name\", type text}, {\"Location\", type text}, {\"Lead time\", Int64.Type}, {\"Production volumes\", Int64.Type}, {\"Manufacturing lead time\", Int64.Type}, {\"Manufacturing costs\", type number}, {\"Inspection results\", type text}, {\"Defect rates\", type number}, {\"Transportation modes\", type text}, {\"Routes\", type text}, {\"Costs\", type number}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"Customer demographics\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Removed Duplicates\", \"Custom\", each if [Customer demographics] = \"Non-binary\" then 3 else if [Customer demographics] = \"Female\" then 2 else if [Customer demographics] = \"Unknown\" then 4 else if [Customer demographics] = \"Male\" then 1 else null, type number),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Conditional Column\",{{\"Custom\", \"cust_demo_id\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_shiping_carriers",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Shipping carriers",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc884b8a-51bc-40cc-a725-e422844af538",
            "sourceColumn": "Shipping carriers",
            "summarizeBy": "none"
          },
          {
            "name": "ship_carriers_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "1aac3240-4449-42b7-99fa-67e83c9c099e",
            "sourceColumn": "ship_carriers_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7ddb3252-367b-46df-8142-7fb52c71ee9f",
        "partitions": [
          {
            "name": "dim_shiping_carriers",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"H:\\_Portfolio Project Github\\Supply Chain Dashboard\\Supply Chain Dashboard Live.xlsx\"), null, true),",
                "    supply_chain_data_Sheet = Source{[Item=\"supply_chain_data\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(supply_chain_data_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Product type\", type text}, {\"SKU\", type text}, {\"Price\", type number}, {\"Availability\", Int64.Type}, {\"Number of products sold\", Int64.Type}, {\"Revenue generated\", type number}, {\"Customer demographics\", type text}, {\"Stock levels\", Int64.Type}, {\"Lead times\", Int64.Type}, {\"Order quantities\", Int64.Type}, {\"Shipping times\", Int64.Type}, {\"Shipping carriers\", type text}, {\"Shipping costs\", type number}, {\"Supplier name\", type text}, {\"Location\", type text}, {\"Lead time\", Int64.Type}, {\"Production volumes\", Int64.Type}, {\"Manufacturing lead time\", Int64.Type}, {\"Manufacturing costs\", type number}, {\"Inspection results\", type text}, {\"Defect rates\", type number}, {\"Transportation modes\", type text}, {\"Routes\", type text}, {\"Costs\", type number}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"Shipping carriers\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Removed Duplicates\", \"Custom\", each if [Shipping carriers] = \"Carrier B\" then 2 else if [Shipping carriers] = \"Carrier A\" then 1 else if [Shipping carriers] = \"Carrier C\" then 3 else null, type number),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Conditional Column\",{{\"Custom\", \"ship_carriers_id\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_suppliers_name",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Supplier name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ecc6280-0545-43e4-aedc-3fccbf48042e",
            "sortByColumn": "supplier_id",
            "sourceColumn": "Supplier name",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "de9798cd-6674-427b-9b1f-528ab454c7de",
            "sourceColumn": "supplier_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6ac96b02-4576-4add-adfc-94ba3bd38b97",
        "partitions": [
          {
            "name": "dim_suppliers_name",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"H:\\_Portfolio Project Github\\Supply Chain Dashboard\\Supply Chain Dashboard Live.xlsx\"), null, true),",
                "    supply_chain_data_Sheet = Source{[Item=\"supply_chain_data\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(supply_chain_data_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Product type\", type text}, {\"SKU\", type text}, {\"Price\", type number}, {\"Availability\", Int64.Type}, {\"Number of products sold\", Int64.Type}, {\"Revenue generated\", type number}, {\"Customer demographics\", type text}, {\"Stock levels\", Int64.Type}, {\"Lead times\", Int64.Type}, {\"Order quantities\", Int64.Type}, {\"Shipping times\", Int64.Type}, {\"Shipping carriers\", type text}, {\"Shipping costs\", type number}, {\"Supplier name\", type text}, {\"Location\", type text}, {\"Lead time\", Int64.Type}, {\"Production volumes\", Int64.Type}, {\"Manufacturing lead time\", Int64.Type}, {\"Manufacturing costs\", type number}, {\"Inspection results\", type text}, {\"Defect rates\", type number}, {\"Transportation modes\", type text}, {\"Routes\", type text}, {\"Costs\", type number}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"Supplier name\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Inserted Text After Delimiter\" = Table.AddColumn(#\"Removed Duplicates\", \"supplier_id\", each Text.AfterDelimiter([Supplier name], \" \"), type text)",
                "in",
                "    #\"Inserted Text After Delimiter\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_location",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "990df37c-a994-4596-99a1-5bfe6fa7fbbc",
            "sourceColumn": "Location",
            "summarizeBy": "none"
          },
          {
            "name": "location_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "f1f556bd-1722-4f4f-b9fe-4f495fc3a538",
            "sourceColumn": "location_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6e92162e-c779-4c4d-8b7c-839e2e37b76b",
        "partitions": [
          {
            "name": "dim_location",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"H:\\_Portfolio Project Github\\Supply Chain Dashboard\\Supply Chain Dashboard Live.xlsx\"), null, true),",
                "    supply_chain_data_Sheet = Source{[Item=\"supply_chain_data\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(supply_chain_data_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Product type\", type text}, {\"SKU\", type text}, {\"Price\", type number}, {\"Availability\", Int64.Type}, {\"Number of products sold\", Int64.Type}, {\"Revenue generated\", type number}, {\"Customer demographics\", type text}, {\"Stock levels\", Int64.Type}, {\"Lead times\", Int64.Type}, {\"Order quantities\", Int64.Type}, {\"Shipping times\", Int64.Type}, {\"Shipping carriers\", type text}, {\"Shipping costs\", type number}, {\"Supplier name\", type text}, {\"Location\", type text}, {\"Lead time\", Int64.Type}, {\"Production volumes\", Int64.Type}, {\"Manufacturing lead time\", Int64.Type}, {\"Manufacturing costs\", type number}, {\"Inspection results\", type text}, {\"Defect rates\", type number}, {\"Transportation modes\", type text}, {\"Routes\", type text}, {\"Costs\", type number}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"Location\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Removed Duplicates\",{{\"Location\", Order.Ascending}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Sorted Rows\", \"location_id\", each if [Location] = \"Bangalore\" then 1 else if [Location] = \"Chennai\" then 2 else if [Location] = \"Delhi\" then 3 else if [Location] = \"Kolkata\" then 4 else if [Location] = \"Mumbai\" then 5 else null, type number)",
                "in",
                "    #\"Added Conditional Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_inspection_result",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Inspection results",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "288a9d52-8306-49eb-9e9b-bfe75043f29d",
            "sourceColumn": "Inspection results",
            "summarizeBy": "none"
          },
          {
            "name": "inspection_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "0a26f827-7590-4a9d-8b22-ee68835cebaa",
            "sourceColumn": "inspection_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3022f6eb-753d-4ad9-bdd5-55e2941145ed",
        "partitions": [
          {
            "name": "dim_inspection_result",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"H:\\_Portfolio Project Github\\Supply Chain Dashboard\\Supply Chain Dashboard Live.xlsx\"), null, true),",
                "    supply_chain_data_Sheet = Source{[Item=\"supply_chain_data\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(supply_chain_data_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Product type\", type text}, {\"SKU\", type text}, {\"Price\", type number}, {\"Availability\", Int64.Type}, {\"Number of products sold\", Int64.Type}, {\"Revenue generated\", type number}, {\"Customer demographics\", type text}, {\"Stock levels\", Int64.Type}, {\"Lead times\", Int64.Type}, {\"Order quantities\", Int64.Type}, {\"Shipping times\", Int64.Type}, {\"Shipping carriers\", type text}, {\"Shipping costs\", type number}, {\"Supplier name\", type text}, {\"Location\", type text}, {\"Lead time\", Int64.Type}, {\"Production volumes\", Int64.Type}, {\"Manufacturing lead time\", Int64.Type}, {\"Manufacturing costs\", type number}, {\"Inspection results\", type text}, {\"Defect rates\", type number}, {\"Transportation modes\", type text}, {\"Routes\", type text}, {\"Costs\", type number}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type\", \"Custom\", each if [Product type] = \"haircare\" then 1 else if [Product type] = \"skincare\" then 2 else if [Product type] = \"cosmetics\" then 3 else null, type number),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Added Conditional Column\",{\"Inspection results\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Removed Duplicates\", \"inspection_id\", each if [Inspection results] = \"Pending\" then 2 else if [Inspection results] = \"Fail\" then 3 else if [Inspection results] = \"Pass\" then 1 else null, type number)",
                "in",
                "    #\"Added Conditional Column1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_transportation_mode",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Transportation modes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "2aba6740-1001-4d44-8d36-b8600e7a9558",
            "sortByColumn": "transportation_id",
            "sourceColumn": "Transportation modes",
            "summarizeBy": "none"
          },
          {
            "name": "transportation_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "3ee77c22-e1b8-42f5-b723-7e0c796cdd2e",
            "sourceColumn": "transportation_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ad82fcfe-cf16-4e07-8c42-943752c6e4fa",
        "partitions": [
          {
            "name": "dim_transportation_mode",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"H:\\_Portfolio Project Github\\Supply Chain Dashboard\\Supply Chain Dashboard Live.xlsx\"), null, true),",
                "    supply_chain_data_Sheet = Source{[Item=\"supply_chain_data\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(supply_chain_data_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Product type\", type text}, {\"SKU\", type text}, {\"Price\", type number}, {\"Availability\", Int64.Type}, {\"Number of products sold\", Int64.Type}, {\"Revenue generated\", type number}, {\"Customer demographics\", type text}, {\"Stock levels\", Int64.Type}, {\"Lead times\", Int64.Type}, {\"Order quantities\", Int64.Type}, {\"Shipping times\", Int64.Type}, {\"Shipping carriers\", type text}, {\"Shipping costs\", type number}, {\"Supplier name\", type text}, {\"Location\", type text}, {\"Lead time\", Int64.Type}, {\"Production volumes\", Int64.Type}, {\"Manufacturing lead time\", Int64.Type}, {\"Manufacturing costs\", type number}, {\"Inspection results\", type text}, {\"Defect rates\", type number}, {\"Transportation modes\", type text}, {\"Routes\", type text}, {\"Costs\", type number}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"Transportation modes\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Removed Duplicates\", \"transportation_id\", each if [Transportation modes] = \"Road\" then 1 else if [Transportation modes] = \"Air\" then 4 else if [Transportation modes] = \"Rail\" then 2 else if [Transportation modes] = \"Sea\" then 3 else null, type number)",
                "in",
                "    #\"Added Conditional Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_routes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Routes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97ad45fa-2671-4835-a7d6-343a6c32a951",
            "sourceColumn": "Routes",
            "summarizeBy": "none"
          },
          {
            "name": "routes_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "cb8aecce-4527-45c4-8c4e-9c9c668301d6",
            "sourceColumn": "routes_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "98749c77-f9f8-4900-a376-2b5bde316451",
        "partitions": [
          {
            "name": "dim_routes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"H:\\_Portfolio Project Github\\Supply Chain Dashboard\\Supply Chain Dashboard Live.xlsx\"), null, true),",
                "    supply_chain_data_Sheet = Source{[Item=\"supply_chain_data\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(supply_chain_data_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Product type\", type text}, {\"SKU\", type text}, {\"Price\", type number}, {\"Availability\", Int64.Type}, {\"Number of products sold\", Int64.Type}, {\"Revenue generated\", type number}, {\"Customer demographics\", type text}, {\"Stock levels\", Int64.Type}, {\"Lead times\", Int64.Type}, {\"Order quantities\", Int64.Type}, {\"Shipping times\", Int64.Type}, {\"Shipping carriers\", type text}, {\"Shipping costs\", type number}, {\"Supplier name\", type text}, {\"Location\", type text}, {\"Lead time\", Int64.Type}, {\"Production volumes\", Int64.Type}, {\"Manufacturing lead time\", Int64.Type}, {\"Manufacturing costs\", type number}, {\"Inspection results\", type text}, {\"Defect rates\", type number}, {\"Transportation modes\", type text}, {\"Routes\", type text}, {\"Costs\", type number}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"Routes\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Removed Duplicates\", \"routes_id\", each if [Routes] = \"Route B\" then 2 else if [Routes] = \"Route C\" then 3 else if [Routes] = \"Route A\" then 1 else null, type number)",
                "in",
                "    #\"Added Conditional Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fact_supply_data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SKU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4691fee8-c88a-4489-91e9-2ac1aecf364f",
            "sourceColumn": "SKU",
            "summarizeBy": "none"
          },
          {
            "name": "Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0d3b7175-4b10-4338-89be-95b223a4a315",
            "sourceColumn": "Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Availability",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4bd18805-dbea-4989-a62c-90e2184ce4d8",
            "sourceColumn": "Availability",
            "summarizeBy": "sum"
          },
          {
            "name": "Number of products sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7838ed96-db46-443a-99a0-99daf6eec3e2",
            "sourceColumn": "Number of products sold",
            "summarizeBy": "sum"
          },
          {
            "name": "Revenue generated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "16321cf6-93d8-4d25-97c3-edab3f33140b",
            "sourceColumn": "Revenue generated",
            "summarizeBy": "sum"
          },
          {
            "name": "Stock levels",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ae1edadc-ff9c-4006-a7a4-7e0defb8637b",
            "sourceColumn": "Stock levels",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Lead Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ac8f7382-9047-40ab-9b55-3e8913275712",
            "sourceColumn": "Order Lead Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Order quantities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4f3def40-eafc-4f46-8e21-220ad72cae86",
            "sourceColumn": "Order quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipping times",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "71f324c4-c619-41be-ae2c-d8eaed154e49",
            "sourceColumn": "Shipping times",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipping costs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d14b9b05-a1d3-43c9-ab7a-9bc0c8a059bf",
            "sourceColumn": "Shipping costs",
            "summarizeBy": "sum"
          },
          {
            "name": "Lead time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8e31ace3-0cba-4a47-baa7-a1d031716be3",
            "sourceColumn": "Lead time",
            "summarizeBy": "sum"
          },
          {
            "name": "Production volumes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dc9d3296-71aa-46e0-9258-9db8edaf638a",
            "sourceColumn": "Production volumes",
            "summarizeBy": "sum"
          },
          {
            "name": "Manufacturing lead time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a074ad6d-67cc-4afe-a1cd-5f861dcd51b4",
            "sourceColumn": "Manufacturing lead time",
            "summarizeBy": "sum"
          },
          {
            "name": "Manufacturing costs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e60175e5-4280-4c4e-af63-83742394ac44",
            "sourceColumn": "Manufacturing costs",
            "summarizeBy": "sum"
          },
          {
            "name": "Defect rates",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c6d0acc5-604c-4743-bbc1-1987ea9e9339",
            "sourceColumn": "Defect rates",
            "summarizeBy": "sum"
          },
          {
            "name": "Costs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8df8fa45-1963-4a33-8757-9ebbf175b34f",
            "sourceColumn": "Costs",
            "summarizeBy": "sum"
          },
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "20b8becf-53cd-4633-9a03-295adcbebeac",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "cust_demo_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "796cc3dc-983e-43ee-b047-91d29d4b894e",
            "sourceColumn": "cust_demo_id",
            "summarizeBy": "none"
          },
          {
            "name": "ship_carriers_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "51bbd73b-f844-44ea-a5fa-0368ca960abf",
            "sourceColumn": "ship_carriers_id",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c0524190-41c3-4283-bb0a-d3879bc38ebc",
            "sourceColumn": "supplier_id",
            "summarizeBy": "none"
          },
          {
            "name": "location_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "819837cd-a37f-4bb0-97b2-c2af1dbf05cd",
            "sourceColumn": "location_id",
            "summarizeBy": "none"
          },
          {
            "name": "inspection_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "7453ced6-97c6-4412-8b2a-ee5d1de4ea2a",
            "sourceColumn": "inspection_id",
            "summarizeBy": "none"
          },
          {
            "name": "transportation_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "00bf2a73-2e6c-4edc-a8fb-8c78a7d90017",
            "sourceColumn": "transportation_id",
            "summarizeBy": "none"
          },
          {
            "name": "routes_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "50ceddb5-993a-40c1-8ce7-ddac8109a5d8",
            "sourceColumn": "routes_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "81b4b7de-7699-4829-bf44-346f0820ae2f",
        "partitions": [
          {
            "name": "Fact_supply_data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"H:\\_Portfolio Project Github\\Supply Chain Dashboard\\Supply Chain Dashboard Live.xlsx\"), null, true),",
                "    supply_chain_data_Sheet = Source{[Item=\"supply_chain_data\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(supply_chain_data_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Product type\", type text}, {\"SKU\", type text}, {\"Price\", type number}, {\"Availability\", Int64.Type}, {\"Number of products sold\", Int64.Type}, {\"Revenue generated\", type number}, {\"Customer demographics\", type text}, {\"Stock levels\", Int64.Type}, {\"Lead times\", Int64.Type}, {\"Order quantities\", Int64.Type}, {\"Shipping times\", Int64.Type}, {\"Shipping carriers\", type text}, {\"Shipping costs\", type number}, {\"Supplier name\", type text}, {\"Location\", type text}, {\"Lead time\", Int64.Type}, {\"Production volumes\", Int64.Type}, {\"Manufacturing lead time\", Int64.Type}, {\"Manufacturing costs\", type number}, {\"Inspection results\", type text}, {\"Defect rates\", type number}, {\"Transportation modes\", type text}, {\"Routes\", type text}, {\"Costs\", type number}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type\", \"product_id\", each if [Product type] = \"haircare\" then 1 else if [Product type] = \"skincare\" then 2 else if [Product type] = \"cosmetics\" then 3 else null, type number),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Conditional Column\",{\"Product type\"}),",
                "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Removed Columns\", \"cust_demo_id\", each if [Customer demographics] = \"Female\" then 2 else if [Customer demographics] = \"Unknown\" then 4 else if [Customer demographics] = \"Non-binary\" then 3 else if [Customer demographics] = \"Male\" then 1 else null, type number),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Added Conditional Column1\",{\"Customer demographics\"}),",
                "    #\"Added Conditional Column2\" = Table.AddColumn(#\"Removed Columns1\", \"ship_carriers_id\", each if [Shipping carriers] = \"Carrier B\" then 2 else if [Shipping carriers] = \"Carrier A\" then 1 else if [Shipping carriers] = \"Carrier C\" then 3 else null, type number),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Conditional Column2\",{\"Shipping carriers\"}),",
                "    #\"Inserted Text After Delimiter\" = Table.AddColumn(#\"Removed Columns2\", \"supplier_id\", each Text.AfterDelimiter([Supplier name], \" \"), type text),",
                "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Inserted Text After Delimiter\",{\"Supplier name\"}),",
                "    #\"Added Conditional Column3\" = Table.AddColumn(#\"Removed Columns3\", \"location_id\", each if [Location] = \"Mumbai\" then 5 else if [Location] = \"Kolkata\" then 4 else if [Location] = \"Delhi\" then 3 else if [Location] = \"Bangalore\" then 1 else if [Location] = \"Chennai\" then 2 else null, type number),",
                "    #\"Removed Columns4\" = Table.RemoveColumns(#\"Added Conditional Column3\",{\"Location\"}),",
                "    #\"Added Conditional Column4\" = Table.AddColumn(#\"Removed Columns4\", \"inspection_id\", each if [Inspection results] = \"Pending\" then 2 else if [Inspection results] = \"Fail\" then 3 else if [Inspection results] = \"Pass\" then 1 else null, type number),",
                "    #\"Removed Columns5\" = Table.RemoveColumns(#\"Added Conditional Column4\",{\"Inspection results\"}),",
                "    #\"Added Conditional Column5\" = Table.AddColumn(#\"Removed Columns5\", \"transportation_id\", each if [Transportation modes] = \"Road\" then 1 else if [Transportation modes] = \"Rail\" then 2 else if [Transportation modes] = \"Air\" then 4 else if [Transportation modes] = \"Sea\" then 3 else null, type number),",
                "    #\"Removed Columns6\" = Table.RemoveColumns(#\"Added Conditional Column5\",{\"Transportation modes\"}),",
                "    #\"Added Conditional Column6\" = Table.AddColumn(#\"Removed Columns6\", \"routes_id\", each if [Routes] = \"Route B\" then 2 else if [Routes] = \"Route C\" then 3 else if [Routes] = \"Route A\" then 1 else null, type number),",
                "    #\"Removed Columns7\" = Table.RemoveColumns(#\"Added Conditional Column6\",{\"Routes\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns7\",{{\"Lead times\", \"Order Lead Time\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "6bfc29a8-06f9-4853-927d-3ebcb6c2156e",
        "measures": [
          {
            "name": "Revenue",
            "expression": "SUM(Fact_supply_data[Revenue generated])",
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "ce0f8af9-ccf6-4fb1-9e83-10493f3edb32"
          },
          {
            "name": "shiping cost",
            "expression": "SUM(Fact_supply_data[Shipping costs])",
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "8342d1e2-5821-4a4d-9367-b12dafc35c41"
          },
          {
            "name": "mfc_cost",
            "expression": "SUM(Fact_supply_data[Manufacturing costs])",
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "66982cf7-9b27-4265-b119-066242b56c1e"
          },
          {
            "name": "cost",
            "expression": "SUM(Fact_supply_data[Costs])",
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "50ee4198-87ef-4b30-9412-cd8be1deda7c"
          },
          {
            "name": "Gross Profit",
            "displayFolder": "_Lead Time Analysis",
            "expression": "[Revenue]-([shiping cost]+[mfc_cost]+[cost])",
            "formatString": "\\$#,0.0;(\\$#,0.0);\\$#,0.0",
            "lineageTag": "5e695edc-9519-4c70-9eb1-cb30687d0c27"
          },
          {
            "name": "Order lead time",
            "expression": "AVERAGE(Fact_supply_data[Order Lead Time])",
            "formatString": "0.00",
            "lineageTag": "5a09c1a3-7c91-40f4-845d-b3c4363deaaa"
          },
          {
            "name": "Lead time",
            "expression": "AVERAGE(Fact_supply_data[Lead time])",
            "formatString": "0.00",
            "lineageTag": "85bece42-b3bf-4633-9855-a7c06535c75a"
          },
          {
            "name": "Shiping time",
            "expression": "AVERAGE(Fact_supply_data[Shipping times])",
            "formatString": "0.00",
            "lineageTag": "a55db00b-744c-4712-b035-4fdf889df36a"
          },
          {
            "name": "Mfc Lead time",
            "expression": "AVERAGE(Fact_supply_data[Manufacturing lead time])",
            "formatString": "0.00",
            "lineageTag": "551161d6-b2ef-425c-a749-43323e5e9caa"
          },
          {
            "name": "Stock Lavel",
            "expression": [
              "",
              " VAR _cal = FORMAT(AVERAGE(Fact_supply_data[Stock levels]),\"#.##\")",
              "RETURN",
              "CONCATENATE(_cal, \"%\")"
            ],
            "lineageTag": "6b530821-80a0-4811-b277-f5a54d3b42eb"
          },
          {
            "name": "Deffect Item",
            "expression": [
              "",
              "VAR deftect_items = FORMAT(AVERAGE(Fact_supply_data[Defect rates]), \"#.##\")",
              "RETURN",
              "CONCATENATE(deftect_items,\"%\")",
              ""
            ],
            "lineageTag": "00a3d9df-d093-4900-b42a-6bf319a53bd3"
          },
          {
            "name": "Production Volume",
            "expression": "SUM(Fact_supply_data[Production volumes])",
            "formatStringDefinition": {
              "expression": "\"#,0.00\""
            },
            "lineageTag": "1dcd42f3-c95b-4bdc-bbf7-68fceb375318"
          },
          {
            "name": "Total Saleble Stock",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUMX(Fact_supply_data, Fact_supply_data[Production volumes]*Fact_supply_data[Stock levels]/100)",
            "lineageTag": "53acc7d3-28a3-4ddb-bb60-d7694356d95e"
          },
          {
            "name": "% Deffect Items",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(Fact_supply_data[Defect rates])",
            "lineageTag": "9bf0a6ff-51aa-4632-8a9e-587e9ed484ed"
          },
          {
            "name": "Risk Factor",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "SUMX(Fact_supply_data, Fact_supply_data[Order Lead Time]*(1-Fact_supply_data[Stock levels]))",
            "formatString": "0",
            "lineageTag": "d9cbf7fd-19bd-445a-a8c9-af7a8566dfb9"
          },
          {
            "name": "Transportation cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[cost]- [mfc_cost] - [shiping cost]",
            "lineageTag": "d95b9ee3-7594-4235-9f93-1a3c035f77e1"
          },
          {
            "name": "Gauge max",
            "displayFolder": "_Lead Time Analysis",
            "expression": "30",
            "formatString": "0",
            "lineageTag": "8fb8c3b1-c7aa-426e-a9fb-cad701cacaaa"
          },
          {
            "name": "Lead Time Target",
            "displayFolder": "_Lead Time Analysis",
            "expression": "MIN(Fact_supply_data[Lead time])+10",
            "formatString": "0",
            "lineageTag": "f64b31a5-266f-45b6-bcfe-238a356fe55e"
          },
          {
            "name": "Lead time color",
            "displayFolder": "_Lead Time Analysis",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [Lead time]>[Lead Time Target],",
              "    \"#C83600\",",
              "    \"#00C000\")"
            ],
            "lineageTag": "199275b5-af0e-4008-b62b-4382066fb295"
          },
          {
            "name": "Risk Factor Color",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [Risk Factor] > -30, \"#C83600\",",
              "    [Risk Factor] > -80, \"#FFA500\",",
              "    [Risk Factor] > -12000000 ,\"#00C000\"",
              ")"
            ],
            "lineageTag": "64dc0b7a-b0f2-43a3-ba4e-ab5b58f04b7d"
          },
          {
            "name": "Order lead time target",
            "displayFolder": "_Lead Time Analysis",
            "expression": "MIN(Fact_supply_data[Order Lead Time])+10",
            "formatString": "0",
            "lineageTag": "c886d1ba-3576-44ca-b286-7158defbd310"
          },
          {
            "name": "Color Order_leadtime",
            "displayFolder": "_Lead Time Analysis",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [Order lead time]>[Order lead time target],",
              "    \"#C83600\",",
              "    \"#00C000\")"
            ],
            "lineageTag": "ab310a32-1c2f-4fd7-bed7-0cdf48baf0a4"
          },
          {
            "name": "MFC_lead time target",
            "displayFolder": "_Lead Time Analysis",
            "expression": "MIN(Fact_supply_data[Manufacturing lead time])+10",
            "formatString": "0",
            "lineageTag": "64e55038-d8e7-4e2e-a3c8-def7b19255de"
          },
          {
            "name": "Color_MFC",
            "displayFolder": "_Lead Time Analysis",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [Mfc Lead time]>[MFC_lead time target],",
              "    \"#C83600\",",
              "    \"#00C000\")"
            ],
            "lineageTag": "7ca07cb2-cf06-4ff5-93e4-a7eee8302e0a"
          },
          {
            "name": "Shiptime Target",
            "displayFolder": "_Lead Time Analysis",
            "expression": "MIN(Fact_supply_data[Shipping times]) +2",
            "formatString": "0",
            "lineageTag": "3b9ebf71-4563-4ca2-bca1-584691d1553f"
          },
          {
            "name": "Color_Shiptime",
            "displayFolder": "_Lead Time Analysis",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [Shiping time] > [Shiptime Target],",
              "    \"#C83600\",",
              "    \"#00C000\")"
            ],
            "lineageTag": "4890ec32-2e7a-4b96-94b2-a65d1aec02c0"
          }
        ],
        "partitions": [
          {
            "name": "_measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}